DROP TABLE IF EXISTS guesses;
DROP TABLE IF EXISTS nominee_people;
DROP TABLE IF EXISTS nominations;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS users;
