-- Populate categories
INSERT INTO categories (name) VALUES
('Best Picture'),
('Best Actor'),
('Best Actress'),
('Best Supporting Actor'),
('Best Supporting Actress'),
('Best Director'),
('Best Adapted Screenplay'),
('Best Original Screenplay'),
('Best Original Song'),
('Best Original Score'),
('Best International Feature'),
('Best Animated Feature'),
('Best Documentary Feature'),
('Best Costume Design'),
('Best Makeup and Hairstyling'),
('Best Production Design'),
('Best Sound'),
('Best Film Editing'),
('Best Cinematography'),
('Best Visual Effects'),
('Best Live Action Short'),
('Best Animated Short'),
('Best Documentary Short');

-- Populate movies
INSERT INTO movies (title, country) VALUES
('Anora', NULL),
('The Brutalist', NULL),
('A Complete Unknown', NULL),
('Conclave', NULL),
('Dune: Part Two', NULL),
('Emilia Pérez', 'France'),
('I''m Still Here', 'Brazil'),
('Nickel Boys', NULL),
('The Substance', NULL),
('Wicked', NULL),
('Sing Sing', NULL),
('The Apprentice', NULL),
('A Real Pain', NULL),
('Maria', NULL),
('Gladiator II', NULL),
('Nosferatu', NULL),
('The Girl with the Needle', 'Denmark'),
('The Seed of the Sacred Fig', 'Germany'),
('Black Box Diaries', NULL),
('No Other Land', NULL),
('Porcelain War', NULL),
('Soundtrack to a Coup d''Etat', NULL),
('Sugarcane', NULL),
('Anuja', NULL),
('I''m Not a Robot', NULL),
('The Last Ranger', NULL),
('A Lien', NULL),
('The Man Who Could Not Remain Silent', NULL),
('A Different Man', NULL),
('Alien: Romulus', NULL),
('Better Man', NULL),
('Kingdom of the Planet of the Apes', NULL),
('Beautiful Men', NULL),
('In the Shadow of the Cypress', NULL),
('Magic Candies', NULL),
('Wander to Wonder', NULL),
('Yuck!', NULL),
('Death by Numbers', NULL),
('I Am Ready, Warden', NULL),
('Incident', NULL),
('Instruments of a Beating Heart', NULL),
('The Only Girl in the Orchestra', NULL),
('September 5', NULL),
('Elton John: Never Too Late', NULL),
('The Six Triple Eight', NULL),
('Flow', 'Latvia'),
('Inside Out 2', NULL),
('Memoir of a Snail', NULL),
('Wallace & Gromit: Vengeance Most Fowl', NULL),
('The Wild Robot', NULL);
